name: ${CHATTER_ROLE:-teleop}

services:
  chatter:
    build: .
    network_mode: host
    environment:
      - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
      - ROS_DISCOVERY_SERVER=ds-host:11811
    command: >
      bash -c "
        source /opt/ros/iron/setup.bash &&
        ros2 run teleop_twist_keyboard teleop_twist_keyboard --ros-args -r /cmd_vel:=/cmd_vel
      "