name: ${CHATTER_ROLE:-robot}

services:
  chatter:
    build: .
    network_mode: host
    environment:
      - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
      - ROS_DISCOVERY_SERVER=ds-host:11811
    command: >
      bash -c "
        source /opt/ros/iron/setup.bash &&
        ros2 topic echo /cmd_vel
      "