name: ${CHATTER_ROLE:-robot}

services:
  chatter:
    build: .
    network_mode: host
    environment:
      - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
      - ROS_DISCOVERY_SERVER=[fc94:ae9e:2a5f:8b44:ea23:e30e:b4b4:7eb0]:11811
    command: >
      bash -c "
        source /opt/ros/jazzy/setup.bash &&
        ros2 topic echo /cmd_vel geometry_msgs/msg/Twist --qos-reliability reliable 
      "