name: ${CHATTER_ROLE:-talker}

services:
  chatter:
    build: .
    network_mode: host
    environment:
      - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
      - ROS_DISCOVERY_SERVER=ds-host:11811
    command: ros2 run demo_nodes_cpp ${CHATTER_ROLE:-talker}